### ISSUE TITLE
Use environment variables for configuration

### ISSUE THREAD

**Issue by jpic** [vmalguy/nessus2jira#1]
Currently, configuration is hardcoded in the script. Perhaps it would be easier to use it if it would use environment variables for configuration, ie. `nessus_api_key = os.environ.get('NESSUS_API_KEY', '')`.

Nice script !

**Comment by vmalguy** [comment]
Environment ? 
Come on , I am better than that ! 
[see commit 9b4632c26f4b21302adcd47e36602aa322c64096](https://github.com/vmalguy/nessus2jira/commit/9b4632c26f4b21302adcd47e36602aa322c64096)

btw : is it the right way to handle issue on Github ?
