### ISSUE TITLE
Import Nessus 2 Jira from File

### ISSUE THREAD

**Issue by stuntpants** [vmalguy/nessus2jira#3]
Hi

I would like to use this to import a .nessus file that has been exported from a Nessus scan on a different network. Is there a way to make the source to be a file rather than the script logging in to Nessus to extract the scan info? Please can someone point me in the direction of how to make this work?

**Comment by vmalguy** [comment]
This script data input is from Nessus API. This is build in his core. A lot need to  be done to change that. You might use some of the function related to JIRA API but basically this is a completely different project.

**Comment by stuntpants** [comment]
Many thanks for you quick response
